# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by Co-Pilot                      ║
# ╙                                                          ╜

import json
from pathlib import Path

import pytest

# This depends on the `attribute_plugin` in our tooling repository
from attribute_plugin import add_test_properties  # type: ignore[import-untyped]

from src.extensions.score_source_code_linker.testlink import (
    DataForTestLink,
    DataForTestLink_JSON_Decoder,
    DataForTestLink_JSON_Encoder,
    DataOfTestCase,
    DataOfTestCase_JSON_Decoder,
    DataOfTestCase_JSON_Encoder,
    load_data_of_test_case_json,
    load_test_xml_parsed_json,
    store_data_of_test_case_json,
    store_test_xml_parsed_json,
)


@add_test_properties(
    partially_verifies=["tool_req__docs_test_link_testcase"],
    test_type="requirements-based",
    derivation_technique="requirements-analysis",
)
def test_testlink_serialization_roundtrip():
    """Ensure that Encode/Decode is reversible"""
    link = DataForTestLink(
        name="my_test",
        file=Path("some/file.py"),
        line=123,
        need="REQ_001",
        verify_type="fully",
        result="passed",
        result_text="All good",
        # ADAPTED: Added new fields
        repo_name="test_repo",
        hash="abc12345",
        url="https://github.com/org/repo",
    )
    dumped = json.dumps(link, cls=DataForTestLink_JSON_Encoder)
    loaded = json.loads(dumped, object_hook=DataForTestLink_JSON_Decoder)

    assert isinstance(loaded, DataForTestLink)
    assert loaded == link


def test_testlink_encoder_handles_path():
    data = {"file": Path("some/thing.py")}
    encoded = json.dumps(data, cls=DataForTestLink_JSON_Encoder)
    assert '"file": "some/thing.py"' in encoded


@add_test_properties(
    partially_verifies=["tool_req__docs_test_link_testcase"],
    test_type="requirements-based",
    derivation_technique="requirements-analysis",
)
def test_decoder_ignores_irrelevant_dicts():
    """Ensure Decoder ignores data it doesn't understand"""
    input_data = {"foo": "bar"}
    result = DataForTestLink_JSON_Decoder(input_data)
    assert result == input_data


@add_test_properties(
    partially_verifies=["tool_req__docs_test_link_testcase"],
    test_type="requirements-based",
    derivation_technique="requirements-analysis",
)
def test_clean_text_removes_ansi_and_html_unescapes():
    """
    Test if text clean works as intended. It should remove ANSI color & text styles, as
    well as convert HTML things back to Chars
    """
    raw = "\x1b[31m&lt;b&gt;Warning&lt;/b&gt;\x1b[0m\nExtra line"
    cleaned = DataOfTestCase.clean_text(raw)
    assert cleaned == "<b>Warning</b> Extra line"


@add_test_properties(
    partially_verifies=["tool_req__docs_test_link_testcase"],
    test_type="requirements-based",
    derivation_technique="requirements-analysis",
)
def test_testcaseneed_to_dict_multiple_links():
    """
    Ensure that a DataOfTestCase can transform itself into a list of DataForTestLink.
    """
    case = DataOfTestCase(
        name="TC_01",
        file="src/test.py",
        line="10",
        result="failed",
        TestType="unit",
        DerivationTechnique="manual",
        result_text="Something went wrong",
        PartiallyVerifies="REQ-1, REQ-2",
        FullyVerifies="REQ-3",
        # ADAPTED: Added new fields which are now required for valid TestLinks
        repo_name="test_repo",
        hash="hash123",
        url="http://github.com",
    )

    links = case.get_test_links()

    assert len(links) == 3
    need_ids = [link.need for link in links]
    assert set(need_ids) == {"REQ-1", "REQ-2", "REQ-3"}

    for link in links:
        assert link.file == Path("src/test.py")
        assert link.line == 10
        assert link.name == "TC_01"
        assert link.result == "failed"
        # ADAPTED: Verify new fields are propagated
        assert link.repo_name == "test_repo"
        assert link.hash == "hash123"
        assert link.url == "http://github.com"


@add_test_properties(
    partially_verifies=["tool_req__docs_test_link_testcase"],
    test_type="requirements-based",
    derivation_technique="requirements-analysis",
)
def test_store_and_load_testlinks_roundtrip(tmp_path: Path):
    """Ensure that Encode/Decode is reversible"""
    file = tmp_path / "testlinks.json"

    links = [
        DataForTestLink(
            name="L1",
            file=Path("abc.py"),
            line=1,
            need="REQ_A",
            verify_type="partially",
            result="passed",
            result_text="Looks good",
            # ADAPTED: Added new fields
            repo_name="mod1",
            hash="h1",
            url="u1",
        ),
        DataForTestLink(
            name="L2",
            file=Path("def.py"),
            line=2,
            need="REQ_B",
            verify_type="fully",
            result="failed",
            result_text="Needs work",
            # ADAPTED: Added new fields
            repo_name="mod2",
            hash="h2",
            url="u2",
        ),
    ]

    store_test_xml_parsed_json(file, links)
    assert file.exists()

    reloaded = load_test_xml_parsed_json(file)

    assert reloaded == links
    for link in reloaded:
        assert isinstance(link, DataForTestLink)


def test_datafortestlink_to_dict_full():
    """Cover line 85: to_dict_full includes all fields"""
    link = DataForTestLink(
        name="test_full",
        file=Path("src/test.py"),
        line=10,
        need="REQ_1",
        verify_type="fully",
        result="passed",
        result_text="All good",
        repo_name="test_repo",
        hash="abc123",
        url="https://github.com/test/repo",
    )
    result = link.to_dict_full()

    assert result["repo_name"] == "test_repo"
    assert result["hash"] == "abc123"
    assert result["url"] == "https://github.com/test/repo"
    assert result["name"] == "test_full"


def test_datafortestlink_equality_with_non_testlink():
    """Cover line 69: __eq__ with non-DataForTestLink returns NotImplemented"""
    link = DataForTestLink(
        name="test",
        file=Path("src/test.py"),
        line=10,
        need="REQ_1",
        verify_type="fully",
        result="passed",
    )

    result = link.__eq__("not a testlink")
    assert result is NotImplemented


#            ──────────────────────[ DataOfTestCase ]──────────────────────


def test_dataoftestcase_check_verifies_fields_missing_both():
    """Cover lines 200-206: check_verifies_fields returns False when both are None"""
    case = DataOfTestCase(
        name="TC_Missing",
        file="src/test.py",
        line="10",
        result="passed",
        TestType="unit",
        DerivationTechnique="manual",
        result_text="",
        PartiallyVerifies=None,
        FullyVerifies=None,
        repo_name="mod",
        hash="h",
        url="u",
    )

    assert case.check_verifies_fields() is False


def test_dataoftestcase_is_valid_fails_on_none_field():
    """Cover lines 232-238: is_valid returns False when required field is None"""
    case = DataOfTestCase(
        name="TC_Invalid",
        file=None,  # Missing required field
        line="10",
        result="passed",
        TestType="unit",
        DerivationTechnique="manual",
        result_text="",
        PartiallyVerifies="REQ_1",
        repo_name="mod",
        hash="h",
        url="u",
    )

    assert case.is_valid() is False


def test_dataoftestcase_get_test_links_returns_empty_when_invalid():
    """Cover line 245: get_test_links returns [] when is_valid is False"""
    case = DataOfTestCase(
        name="TC_Invalid",
        file=None,  # Invalid
        line="10",
        result="passed",
        TestType="unit",
        DerivationTechnique="manual",
        PartiallyVerifies="REQ_1",
    )

    links = case.get_test_links()
    assert links == []


def test_dataoftestcase_decoder_valid_dict():
    """Cover lines 314-324: Decoder reconstructs DataOfTestCase from valid dict"""
    json_data = {
        "name": "TC_01",
        "file": "src/test.py",
        "line": "10",
        "result": "passed",
        "TestType": "unit",
        "DerivationTechnique": "manual",
        "result_text": "Good",
        "PartiallyVerifies": "REQ_1",
        "FullyVerifies": "REQ_2",
        "repo_name": "mod",
        "hash": "h",
        "url": "u",
    }
    result = DataOfTestCase_JSON_Decoder(json_data)

    assert isinstance(result, DataOfTestCase)
    assert result.name == "TC_01"
    assert result.file == "src/test.py"


def test_dataoftestcase_decoder_non_testcase_dict():
    """Cover line 326: Decoder returns dict unchanged for non-TestCase data"""
    json_data = {"some": "other", "data": "here"}
    result = DataOfTestCase_JSON_Decoder(json_data)
    assert result == json_data


def test_store_and_load_data_of_test_case_roundtrip(tmp_path: Path):
    """Cover lines 376-386: store and load DataOfTestCase roundtrip"""
    test_cases = [
        DataOfTestCase(
            name="TC_A",
            file="src/a.py",
            line="5",
            result="passed",
            TestType="unit",
            DerivationTechnique="manual",
            result_text="OK",
            PartiallyVerifies="REQ_A",
            FullyVerifies=None,
            repo_name="mod_a",
            hash="hash_a",
            url="url_a",
        ),
        DataOfTestCase(
            name="TC_B",
            file="src/b.py",
            line="15",
            result="failed",
            TestType="integration",
            DerivationTechnique="auto",
            result_text="Failed",
            PartiallyVerifies=None,
            FullyVerifies="REQ_B",
            repo_name="mod_b",
            hash="hash_b",
            url="url_b",
        ),
    ]

    test_file = tmp_path / "test_cases.json"
    store_data_of_test_case_json(test_file, test_cases)
    loaded = load_data_of_test_case_json(test_file)

    assert len(loaded) == 2
    assert loaded[0].name == "TC_A"
    assert loaded[1].name == "TC_B"


def test_load_data_of_test_case_validates_list(tmp_path: Path):
    """Cover line 380: Load validates result is a list"""
    test_file = tmp_path / "not_list.json"
    test_file.write_text('{"name": "TC_01"}')

    with pytest.raises(AssertionError, match="should be a list"):
        _ = load_data_of_test_case_json(test_file)


def test_load_data_of_test_case_validates_items(tmp_path: Path):
    """Cover line 383: Load validates all items are DataOfTestCase"""
    test_file = tmp_path / "invalid_items.json"
    test_file.write_text('[{"invalid": "structure"}]')

    with pytest.raises(AssertionError, match="should be TestCaseNeed objects"):
        _ = load_data_of_test_case_json(test_file)


def test_dataoftestcase_encoder_fallback():
    """Cover line 299: Encoder falls back to parent for unknown types"""
    encoder = DataOfTestCase_JSON_Encoder()

    # This should trigger the super().default() call
    with pytest.raises(TypeError):
        _ = encoder.default(object())


def test_datafortestlink_encoder_fallback():
    """Cover line 103: DataForTestLink encoder falls back to parent for unknown types"""
    from src.extensions.score_source_code_linker.testlink import (
        DataForTestLink_JSON_Encoder,
    )

    encoder = DataForTestLink_JSON_Encoder()

    # This should trigger the super().default() call
    with pytest.raises(TypeError):
        _ = encoder.default(object())


def test_datafortestlink_decoder_non_testlink_dict():
    """Cover line 132: DataForTestLink decoder returns dict unchanged"""
    from src.extensions.score_source_code_linker.testlink import (
        DataForTestLink_JSON_Decoder,
    )

    json_data = {"random": "data", "other": "stuff"}
    result = DataForTestLink_JSON_Decoder(json_data)
    assert result == json_data
