# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by CoPilot                       ║
# ╙                                                          ╜

from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace
from typing import cast

import pytest
import score_metamodel.external_needs as ext_needs
from score_metamodel.external_needs import (
    ExternalNeedsSource,
    _add_needs_json_file,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    _external_needs_runfiles_path,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    _external_needs_source_path,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    _runfiles_dir,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    add_external_needs_json,
    get_external_needs_source,
)
from sphinx.config import Config
from sphinx_needs.needsfile import NeedsList

from src.helper_lib.external_needs import (
    parse_bazel_external_need,
    parse_external_needs_labels,
)


def test_extend_needs_json_exporter_uses_configured_value(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The exporter reads the current project URL from Sphinx configuration."""
    config = Config()
    config.project_url = "https://example.test/before"

    monkeypatch.setattr(NeedsList, "_finalise", lambda _needs_list: None)
    ext_needs.extend_needs_json_exporter(config, ["project_url"])
    config.project_url = "https://example.test/after"

    needs_list = cast(NeedsList, SimpleNamespace(needs_list={}))
    NeedsList._finalise(needs_list)  # pyright: ignore[reportPrivateUsage] - white-box test

    assert needs_list.needs_list["project_url"] == "https://example.test/after"


def test_extend_needs_json_exporter_can_override_export_metadata(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """An explicit export override wins while Sphinx keeps the config value."""
    config = Config()
    config.project_url = "https://example.test/host"

    monkeypatch.setattr(NeedsList, "_finalise", lambda _needs_list: None)
    ext_needs.extend_needs_json_exporter(
        config,
        ["project_url"],
        log_missing=False,
        export_values={"project_url": ""},
    )

    needs_list = cast(NeedsList, SimpleNamespace(needs_list={}))
    NeedsList._finalise(needs_list)  # pyright: ignore[reportPrivateUsage] - white-box test

    assert config.project_url == "https://example.test/host"
    assert needs_list.needs_list["project_url"] == ""


@pytest.mark.parametrize(
    ("source", "suffix", "expected"),
    [
        (
            ExternalNeedsSource(
                bazel_module="repo",
                path_to_target="docs",
                target="needs_json",
            ),
            ("needs_json", "_build", "needs", "needs.json"),
            Path("/runfiles/repo+/docs/needs_json/_build/needs/needs.json"),
        ),
    ],
)
def test_external_needs_runfiles_path_is_environment_independent(
    source: ExternalNeedsSource, suffix: tuple[str, ...], expected: Path
) -> None:
    assert _external_needs_runfiles_path(Path("/runfiles"), source, *suffix) == expected


def test_parse_bazel_external_need_marks_same_repository_labels_local() -> None:
    assert parse_bazel_external_need("//pkg:needs_json") == ExternalNeedsSource(
        bazel_module="",
        path_to_target="pkg",
        target="needs_json",
        is_local=True,
    )


def test_parse_external_needs_labels_filters_ordinary_data_labels() -> None:
    assert parse_external_needs_labels(
        ["docs/index.rst", "//pkg:needs_json", "assets/logo.svg"]
    ) == [
        ExternalNeedsSource(
            bazel_module="",
            path_to_target="pkg",
            target="needs_json",
            is_local=True,
        )
    ]


@pytest.mark.parametrize(
    ("source", "expected"),
    [
        (
            ExternalNeedsSource(
                bazel_module="repo",
                path_to_target="docs",
                target="needs_json",
            ),
            Path("/runfiles/repo+/docs/needs_json/_build/needs/needs.json"),
        ),
        (
            ExternalNeedsSource(
                bazel_module="repo",
                path_to_target="docs",
                target="needs_json_file",
            ),
            Path("/runfiles/repo+/docs/needs.json"),
        ),
    ],
)
def test_external_needs_source_path_selects_target_layout(
    source: ExternalNeedsSource, expected: Path
) -> None:
    assert _external_needs_source_path(Path("/runfiles"), source) == expected


def test_configured_runfiles_dir_is_used_for_external_sources(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    config = Config()
    configured_runfiles = tmp_path / "configured.runfiles"
    config.runfiles_dir = str(configured_runfiles)

    monkeypatch.setattr(
        ext_needs,
        "get_runfiles_dir",
        lambda: pytest.fail("configured runfiles root should be preferred"),
    )

    assert _runfiles_dir(config) == configured_runfiles


def test_external_needs_source_config_parses_labels() -> None:
    raw = json.dumps(
        ["@vendor//:needs_json"],
    )

    sources = get_external_needs_source(raw)

    assert sources == [
        ExternalNeedsSource(
            bazel_module="vendor",
            path_to_target="",
            target="needs_json",
        )
    ]
    assert _external_needs_source_path(Path("/runfiles"), sources[0]) == Path(
        "/runfiles/vendor+/needs_json/_build/needs/needs.json"
    )


def test_external_needs_source_rejects_descriptors() -> None:
    with pytest.raises(ValueError, match="Bazel label strings"):
        get_external_needs_source(
            json.dumps(
                [
                    {
                        "bazel_module": "vendor",
                        "path_to_target": "",
                        "target": "needs_json",
                    }
                ]
            )
        )


def test_add_external_needs_json_appends_entry(
    tmp_path: Path,
) -> None:
    """add_external_needs_json should append one external needs mapping entry."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    runfiles_dir = tmp_path
    rel_json = Path("ext_mod+/needs_json/_build/needs/needs.json")
    json_path = runfiles_dir / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/repo"}), encoding="utf-8"
    )

    add_external_needs_json(e, config, runfiles_dir)

    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/repo/main"
    assert Path(entry["json_path"]) == json_path


def test_add_external_needs_json_appends_entry_local(
    tmp_path: Path,
) -> None:
    """A same-repo mount resolves under `_main/<path>/<target>/…`."""
    e = ExternalNeedsSource(
        bazel_module="",
        target="needs_json",
        path_to_target="src/tests/e2e/external_needs/producer",
        is_local=True,
    )
    config = Config()
    config.needs_external_needs = []

    runfiles_dir = tmp_path
    rel_json = Path(
        "_main/src/tests/e2e/external_needs/producer/needs_json/_build/needs/needs.json"
    )
    json_path = runfiles_dir / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/local"}), encoding="utf-8"
    )

    add_external_needs_json(e, config, runfiles_dir)

    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/local/main"
    assert Path(entry["json_path"]) == json_path


def test_add_needs_json_file_appends_entry(
    tmp_path: Path,
) -> None:
    """_add_needs_json_file should load from a :needs_json_file target."""
    # Arrange: create the needs.json at the runfiles path
    rel_json = Path("ext_mod+/needs.json")
    json_path = tmp_path / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/json-file"}), encoding="utf-8"
    )

    runfiles_dir = tmp_path
    config = Config()
    config.needs_external_needs = []

    # Act
    e = ExternalNeedsSource(
        bazel_module="ext_mod",
        target="needs_json_file",
        path_to_target="",
        is_local=False,
    )
    _add_needs_json_file(e, config, runfiles_dir)

    # Assert
    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/json-file/main"
    assert Path(entry["json_path"]) == json_path


def test_add_external_needs_json_missing_file_keeps_list_empty(
    tmp_path: Path,
) -> None:
    """add_external_needs_json should return gracefully when JSON file is missing."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    add_external_needs_json(e, config, tmp_path)

    # Assert
    assert config.needs_external_needs == []
