# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some portions generated by CoPilot                       ║
# ╙                                                          ╜

from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace
from typing import cast

import pytest
import score_metamodel.external_needs as ext_needs
from score_metamodel.external_needs import (
    ExternalNeedsSource,
    _add_needs_json_file,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    _external_needs_runfiles_path,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    _external_needs_source_path,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    _runfiles_dir,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    _warn_for_duplicate_external_need_ids,  # pyright: ignore[reportPrivateUsage] - white-box unit test
    add_external_needs_json,
    get_external_needs_source,
)
from sphinx.application import Sphinx
from sphinx.config import Config
from sphinx_needs.needsfile import NeedsList

from src.helper_lib.external_needs import (
    parse_bazel_external_need,
    parse_external_needs_labels,
)


def test_extend_needs_json_exporter_uses_configured_value(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The exporter reads the current project URL from Sphinx configuration."""
    config = Config()
    config.project_url = "https://example.test/before"

    monkeypatch.setattr(NeedsList, "_finalise", lambda _needs_list: None)
    ext_needs.extend_needs_json_exporter(config, ["project_url"])
    config.project_url = "https://example.test/after"

    needs_list = cast(NeedsList, SimpleNamespace(needs_list={}))
    NeedsList._finalise(needs_list)  # pyright: ignore[reportPrivateUsage] - white-box test

    assert needs_list.needs_list["project_url"] == "https://example.test/after"


def test_extend_needs_json_exporter_can_override_export_metadata(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """An explicit export override wins while Sphinx keeps the config value."""
    config = Config()
    config.project_url = "https://example.test/host"

    monkeypatch.setattr(NeedsList, "_finalise", lambda _needs_list: None)
    ext_needs.extend_needs_json_exporter(
        config,
        ["project_url"],
        log_missing=False,
        export_values={"project_url": ""},
    )

    needs_list = cast(NeedsList, SimpleNamespace(needs_list={}))
    NeedsList._finalise(needs_list)  # pyright: ignore[reportPrivateUsage] - white-box test

    assert config.project_url == "https://example.test/host"
    assert needs_list.needs_list["project_url"] == ""


@pytest.mark.parametrize(
    ("source", "suffix", "expected"),
    [
        (
            ExternalNeedsSource(
                bazel_module="repo",
                path_to_target="docs",
                target="needs_json",
            ),
            ("needs_json", "_build", "needs", "needs.json"),
            Path("/runfiles/repo+/docs/needs_json/_build/needs/needs.json"),
        ),
    ],
)
def test_external_needs_runfiles_path_is_environment_independent(
    source: ExternalNeedsSource, suffix: tuple[str, ...], expected: Path
) -> None:
    assert _external_needs_runfiles_path(Path("/runfiles"), source, *suffix) == expected


def test_parse_bazel_external_need_marks_same_repository_labels_local() -> None:
    assert parse_bazel_external_need("//pkg:needs_json") == ExternalNeedsSource(
        bazel_module="",
        path_to_target="pkg",
        target="needs_json",
        is_local=True,
    )


def test_parse_external_needs_labels_filters_ordinary_data_labels() -> None:
    assert parse_external_needs_labels(
        ["docs/index.rst", "//pkg:needs_json", "assets/logo.svg"]
    ) == [
        ExternalNeedsSource(
            bazel_module="",
            path_to_target="pkg",
            target="needs_json",
            is_local=True,
        )
    ]


@pytest.mark.parametrize(
    ("source", "expected"),
    [
        (
            ExternalNeedsSource(
                bazel_module="repo",
                path_to_target="docs",
                target="needs_json",
            ),
            Path("/runfiles/repo+/docs/needs_json/_build/needs/needs.json"),
        ),
        (
            ExternalNeedsSource(
                bazel_module="repo",
                path_to_target="docs",
                target="needs_json_file",
            ),
            Path("/runfiles/repo+/docs/needs.json"),
        ),
    ],
)
def test_external_needs_source_path_selects_target_layout(
    source: ExternalNeedsSource, expected: Path
) -> None:
    assert _external_needs_source_path(Path("/runfiles"), source) == expected


def test_configured_runfiles_dir_is_used_for_external_sources(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    config = Config()
    configured_runfiles = tmp_path / "configured.runfiles"
    config.runfiles_dir = str(configured_runfiles)

    monkeypatch.setattr(
        ext_needs,
        "get_runfiles_dir",
        lambda: pytest.fail("configured runfiles root should be preferred"),
    )

    assert _runfiles_dir(config) == configured_runfiles


def test_external_needs_source_config_parses_labels() -> None:
    raw = json.dumps(
        ["@vendor//:needs_json"],
    )

    sources = get_external_needs_source(raw)

    assert sources == [
        ExternalNeedsSource(
            bazel_module="vendor",
            path_to_target="",
            target="needs_json",
        )
    ]
    assert _external_needs_source_path(Path("/runfiles"), sources[0]) == Path(
        "/runfiles/vendor+/needs_json/_build/needs/needs.json"
    )


def test_external_needs_source_rejects_descriptors() -> None:
    with pytest.raises(ValueError, match="Bazel label strings"):
        get_external_needs_source(
            json.dumps(
                [
                    {
                        "bazel_module": "vendor",
                        "path_to_target": "",
                        "target": "needs_json",
                    }
                ]
            )
        )


def test_add_external_needs_json_appends_entry(
    tmp_path: Path,
) -> None:
    """add_external_needs_json should append one external needs mapping entry."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    runfiles_dir = tmp_path
    rel_json = Path("ext_mod+/needs_json/_build/needs/needs.json")
    json_path = runfiles_dir / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/repo"}), encoding="utf-8"
    )

    add_external_needs_json(e, config, runfiles_dir)

    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/repo/main"
    assert Path(entry["json_path"]) == json_path


def test_add_external_needs_json_appends_entry_local(
    tmp_path: Path,
) -> None:
    """A same-repo mount resolves under `_main/<path>/<target>/…`."""
    e = ExternalNeedsSource(
        bazel_module="",
        target="needs_json",
        path_to_target="src/tests/e2e/external_needs/producer",
        is_local=True,
    )
    config = Config()
    config.needs_external_needs = []

    runfiles_dir = tmp_path
    rel_json = Path(
        "_main/src/tests/e2e/external_needs/producer/needs_json/_build/needs/needs.json"
    )
    json_path = runfiles_dir / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/local"}), encoding="utf-8"
    )

    add_external_needs_json(e, config, runfiles_dir)

    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/local/main"
    assert Path(entry["json_path"]) == json_path


def test_add_needs_json_file_appends_entry(
    tmp_path: Path,
) -> None:
    """_add_needs_json_file should load from a :needs_json_file target."""
    # Arrange: create the needs.json at the runfiles path
    rel_json = Path("ext_mod+/needs.json")
    json_path = tmp_path / rel_json
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(
        json.dumps({"project_url": "https://example.test/json-file"}), encoding="utf-8"
    )

    runfiles_dir = tmp_path
    config = Config()
    config.needs_external_needs = []

    # Act
    e = ExternalNeedsSource(
        bazel_module="ext_mod",
        target="needs_json_file",
        path_to_target="",
        is_local=False,
    )
    _add_needs_json_file(e, config, runfiles_dir)

    # Assert
    assert config.needs_external_needs is not None
    assert len(config.needs_external_needs) == 1
    entry = config.needs_external_needs[0]
    assert entry["base_url"] == "https://example.test/json-file/main"
    assert Path(entry["json_path"]) == json_path


def test_add_external_needs_json_missing_file_keeps_list_empty(
    tmp_path: Path,
) -> None:
    """add_external_needs_json should return gracefully when JSON file is missing."""
    # Arrange
    e = ExternalNeedsSource(
        bazel_module="ext_mod", target="needs_json", path_to_target=""
    )
    config = Config()
    config.needs_external_needs = []

    add_external_needs_json(e, config, tmp_path)

    # Assert
    assert config.needs_external_needs == []


def _write_needs_inventory(
    runfiles_dir: Path,
    source: ExternalNeedsSource,
    *,
    project_url: str,
    need_ids: list[str],
) -> None:
    """Write a minimal versioned Sphinx-Needs inventory at its runfiles path."""
    json_file = _external_needs_source_path(runfiles_dir, source)
    json_file.parent.mkdir(parents=True, exist_ok=True)
    json_file.write_text(
        json.dumps(
            {
                "project_url": project_url,
                "current_version": "1.0",
                "versions": {
                    "1.0": {"needs": {need_id: {"id": need_id} for need_id in need_ids}}
                },
            }
        ),
        encoding="utf-8",
    )


def _external_source(repo: str, target: str) -> ExternalNeedsSource:
    """Create a root-level external-needs target from a Bazel repository."""
    return ExternalNeedsSource(
        bazel_module=repo,
        path_to_target="",
        target=target,
    )


def test_duplicate_external_need_ids_with_same_base_url_are_reported(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """The preflight warns when same-URL inventories contain the same Need ID."""
    sources = [
        _external_source("first_repo", target="needs_json"),
        _external_source("second_repo", target="needs_json_file"),
    ]
    for source in sources:
        _write_needs_inventory(
            tmp_path,
            source,
            project_url="https://example.test/shared",
            need_ids=["REQ-1"],
        )

    config = Config()
    config.external_needs_source = "test sources"
    config.runfiles_dir = str(tmp_path)
    config.score_bundle_needs_export = False

    warnings: list[tuple[str, str, object | None]] = []

    def capture_warning(
        _logger: object,
        message: str,
        warning_type: str,
        location: object | None = None,
    ) -> None:
        # The preflight must report the collision before registering either source.
        assert config.needs_external_needs == []
        warnings.append((message, warning_type, location))

    monkeypatch.setattr(
        ext_needs,
        "extend_needs_json_exporter",
        lambda *_args, **_kwargs: None,
    )
    monkeypatch.setattr(ext_needs, "get_external_needs_source", lambda _raw: sources)
    monkeypatch.setattr(ext_needs, "log_warning", capture_warning)

    app = cast(Sphinx, SimpleNamespace(config=config))
    ext_needs.connect_external_needs(app, config)

    assert len(warnings) == 1
    message, warning_type, location = warnings[0]
    assert warning_type == "load_external_need"
    assert location is None
    assert "REQ-1" in message
    assert "@first_repo//:needs_json" in message
    assert "@second_repo//:needs_json_file" in message
    assert "https://example.test/shared/main" in message
    assert len(config.needs_external_needs) == 2


def test_duplicate_external_need_ids_with_different_base_urls_do_not_warn(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """The preflight only warns when both the base URL and Need ID overlap."""
    sources = [
        _external_source("first_repo", target="needs_json"),
        _external_source("second_repo", target="needs_json"),
    ]
    for source, project_url in zip(
        sources,
        ("https://example.test/first", "https://example.test/second"),
        strict=True,
    ):
        _write_needs_inventory(
            tmp_path,
            source,
            project_url=project_url,
            need_ids=["REQ-1"],
        )

    monkeypatch.setattr(
        ext_needs,
        "log_warning",
        lambda *_args, **_kwargs: pytest.fail("different URLs should not warn here"),
    )

    _warn_for_duplicate_external_need_ids(sources, tmp_path)


def test_same_base_url_without_duplicate_ids_does_not_warn(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    """Sharing a project URL alone is harmless when Need IDs do not overlap."""
    sources = [
        _external_source("first_repo", target="needs_json"),
        _external_source("second_repo", target="needs_json_file"),
    ]
    _write_needs_inventory(
        tmp_path,
        sources[0],
        project_url="https://example.test/shared",
        need_ids=["REQ-1"],
    )
    _write_needs_inventory(
        tmp_path,
        sources[1],
        project_url="https://example.test/shared",
        need_ids=["REQ-2"],
    )

    monkeypatch.setattr(
        ext_needs,
        "log_warning",
        lambda *_args, **_kwargs: pytest.fail("disjoint inventories should not warn"),
    )

    _warn_for_duplicate_external_need_ids(sources, tmp_path)
