repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
        exclude: ^\.vscode/ # those are actually jsonc files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files
        args: ["--maxkb=150"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
        args:
          # Disable shellcheck and pyflakes for now, to enforce consistent behavior.
          - -shellcheck=
          - -pyflakes=

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  # Note: this is super slow, therefore it is last
  - repo: local
    hooks:
      - id: BasedPyright
        name: BasedPyright
        entry: bash -c 'bazel run //:ide_support && .venv_docs/bin/python3 -m basedpyright'
        language: system
        pass_filenames: false
