name: 'Link Check and Automated Issue'
description: 'Checks links, parses results, and creates or updates an issue with findings.'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Run LinkChecker (generates linkcheck_output.txt)
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/link_check.sh
        ${{ github.action_path }}/link_check.sh

    - name: Parse broken links (generates issue_body.md)
      shell: bash
      run: |
        python3 ${{ github.action_path }}/link_parser.py linkcheck_output.txt

    - name: Create or update GitHub issue from findings
      if: success() && hashFiles('issue_body.md') != ''
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const path = require('path');
          const body = fs.readFileSync(path.join(process.cwd(), 'issue_body.md'), 'utf-8');
          const title = "Automated Issue: Broken Documentation Links";

          // Find existing open issue with the same title created by GitHub Actions bot
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: "open",
            creator: "github-actions[bot]",
            labels: undefined,
          });

          const issue = issues.find(i => i.title === title);

          if (issue) {
            // Update the existing issue
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body,
            });
          } else {
            // Create a new issue
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
            });
          }
