# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# ╓                                                          ╖
# ║ Some parts are generated by Gemini                       ║
# ╙                                                          ╜

"""Tests for generate_sourcelinks_cli.py"""

import json
import sys
from pathlib import Path

import pytest

import scripts_bazel.generate_sourcelinks_cli
from src.extensions.score_source_code_linker.needlinks import is_metadata

_MY_PATH = Path(__file__).parent


def assert_json_internal_types(input: list[dict[str, str | int]]):
    for entry in input:
        assert "file" in entry
        assert "line" in entry
        assert "tag" in entry
        assert "need" in entry
        assert "full_line" in entry

        assert isinstance(entry["file"], str)
        assert isinstance(entry["line"], int)
        assert isinstance(entry["tag"], str)
        assert isinstance(entry["need"], str)
        assert isinstance(entry["full_line"], str)


# Unit test generated by Gemini.
@pytest.mark.parametrize(
    "input_path, expected_output",
    [
        # Case 1: Path starts with "external/" and has a project name
        (Path("external/score_docs_as_code+/docs/index.md"), Path("docs/index.md")),
        # Case 2: Path does NOT start with "external/"
        (Path("src/main.py"), Path("src/main.py")),
        # Case 3: Path has "external" elsewhere in the string (should not be removed)
        (Path("my_external_data/file.txt"), Path("my_external_data/file.txt")),
        # Case 4: Deeply nested path inside an external prefix
        (Path("external/repo/subfolder/file.py"), Path("subfolder/file.py")),
        # Case 5: Path is exactly "external/" (edge case, returns empty path based on split logic)
        (Path("external/"), Path("external")),
    ],
)
def test_clean_external_prefix(input_path: Path, expected_output: Path):
    output = scripts_bazel.generate_sourcelinks_cli.clean_external_prefix(input_path)
    assert output == expected_output


def test_generate_sourcelinks_cli_basic(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Test basic functionality of generate_sourcelinks_cli."""
    # Create a test source file with a traceability tag
    test_file = tmp_path / "test_source.py"
    test_file.write_text(
        """
# Some code here
# req-Id: tool_req__docs_arch_types
def some_function():
    pass
"""
    )

    output_file = tmp_path / "output.json"

    test_args: list[Path | str] = [
        _MY_PATH.parent
        / "generate_sourcelinks_cli.py",  # sys.argv[0] is always the script name
        "--output",
        str(output_file),
        str(test_file),
    ]
    monkeypatch.setattr(sys, "argv", test_args)
    result = scripts_bazel.generate_sourcelinks_cli.main()
    assert result == 0

    # Check the output content
    with open(output_file) as f:
        data: list[dict[str, str | int]] = json.load(f)
    assert isinstance(data, list)
    # The first dictionary has to be metadata
    assert len(data) == 2
    assert is_metadata(data[0])
    assert data[0]["repo_name"] == "local_repo"
    # hash & url can not be set in this script therefore HAVE to be empty
    assert data[0]["hash"] == ""
    assert data[0]["url"] == ""

    # Verify schema of each entry
    assert_json_internal_types(data[1:])

    assert data[1]["need"] == "tool_req__docs_arch_types"


def test_generate_sourcelinks_cli_parse_external_module(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    # 1. Create the 'external' directory inside the temp path
    external_root = tmp_path / "external"
    external_root.mkdir()

    # 2. Create your file inside that 'external' directory
    test_file = external_root / "score_baselibs+" / "src" / "source_file1.py"
    test_file.parent.mkdir(parents=True)
    test_file.write_text("content")

    # 3. Create the path relative to tmp_path so it starts with 'external/'
    # Use .relative_to(tmp_path) to get 'external/score_docs_as_code+/...'
    test_file.write_text(
        """
# Some code here
# req-Id: tool_req__docs_arch_types
def some_function():
    pass
"""
    )
    output_file = tmp_path / "output.json"
    monkeypatch.chdir(tmp_path)
    relative_test_file = test_file.relative_to(tmp_path)
    test_args: list[Path | str] = [
        _MY_PATH.parent
        / "generate_sourcelinks_cli.py",  # sys.argv[0] is always the script name
        "--output",
        str(output_file),
        str(relative_test_file),
    ]
    monkeypatch.setattr(sys, "argv", test_args)
    result = scripts_bazel.generate_sourcelinks_cli.main()
    assert result == 0
    with open(output_file) as f:
        data: list[dict[str, str | int]] = json.load(f)
    assert isinstance(data, list)
    assert len(data) == 2
    # The first dictionary has to be metadata
    assert is_metadata(data[0])
    assert data[0]["repo_name"] == "score_baselibs"
    # hash & url can not be set in this script therefore HAVE to be empty
    assert data[0]["hash"] == ""
    assert data[0]["url"] == ""

    # Verify schema of each entry
    assert_json_internal_types(data[1:])


def test_generate_sourcelinks_cli_file_not_exists(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    external_root = tmp_path / "external"
    external_root.mkdir()

    # 2. Create your file inside that 'external' directory
    test_file = external_root / "score_baselibs+" / "src" / "source_file1.py"
    test_file.parent.mkdir(parents=True)
    test_file.write_text("content")

    # 3. Create the path relative to tmp_path so it starts with 'external/'
    # Use .relative_to(tmp_path) to get 'external/score_docs_as_code+/...'
    test_file.write_text(
        """
# Some code here
# req-Id: tool_req__docs_arch_types
def some_function():
    pass
"""
    )
    output_file = tmp_path / "output.json"
    # BY not changing directory (like above) we can FORCE the file to not exists
    relative_test_file = test_file.relative_to(tmp_path)
    test_args: list[Path | str] = [
        _MY_PATH.parent
        / "generate_sourcelinks_cli.py",  # sys.argv[0] is always the script name
        "--output",
        str(output_file),
        str(relative_test_file),
    ]
    monkeypatch.setattr(sys, "argv", test_args)
    with pytest.raises(AssertionError):
        scripts_bazel.generate_sourcelinks_cli.main()
