# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
import matplotlib
from sphinx.application import Sphinx

from src.helper_lib import config_setdefault

# Note: order matters!
# Extensions are loaded in this order.
# e.g. plantuml MUST be loaded before sphinx-needs
score_extensions = [
    "sphinxcontrib.plantuml",
    "score_plantuml",
    "sphinx_needs",
    "score_sphinx_needs_templates",
    "score_cross_module_compatibility",
    "score_metamodel",
    "sphinx_design",
    "myst_parser",
    # sphinx_mounts provides the mount machinery; score_mounts feeds it the
    # Bazel-emitted mount config and must be loaded right after it (its
    # config-inited hook runs before sphinx_mounts' own, see score_mounts.setup).
    "sphinx_mounts",
    "score_mounts",
    "score_source_code_linker",
    "score_draw_uml_funcs",
    "score_layout",
    "sphinxcontrib.mermaid",
    "needs_config_writer",
    "score_sync_toml",
    "score_metrics",
    "broken_link_fix",
]


def setup(app: Sphinx) -> dict[str, object]:
    matplotlib.rcParamsDefault["savefig.bbox"] = "tight"

    # Keep the project URL available when Sphinx runs in configuration-free
    # mode. A normal conf.py can define arbitrary values directly, but CLI
    # overrides require custom settings to be registered first.
    app.add_config_value("project_url", "", rebuild="env")

    config_setdefault(app.config, "html_copy_source", False)
    config_setdefault(app.config, "html_show_sourcelink", False)

    # Global settings
    # Note: the "sub-extensions" also set their own config values

    # Match the current GitHub and VS Code Mermaid renderers.
    config_setdefault(app.config, "mermaid_version", "11.17.2")
    config_setdefault(app.config, "mermaid_d3_zoom", True)
    config_setdefault(app.config, "mermaid_include_elk", True)

    # The following entries are not required when building the documentation via
    # 'bazel build //:docs', as that command runs in a sandboxed environment.
    # However, when building the documentation via 'bazel run //:docs' or esbonio,
    # these entries are required to prevent the build from failing.
    app.config.exclude_patterns += ["bazel-*", ".venv*"]

    # Enable markdown rendering
    app.config.source_suffix.setdefault(".rst", "restructuredtext")
    app.config.source_suffix.setdefault(".md", "markdown")

    if "templates" not in app.config.templates_path:
        app.config.templates_path += ["templates"]

    config_setdefault(app.config, "numfig", True)
    config_setdefault(app.config, "author", "S-CORE")

    # Load the actual extensions list
    for e in score_extensions:
        app.setup_extension(e)

    # Enable cross-reference resolution for [text](file.md#anchor) links up to h4.
    # Without this, MyST treats heading anchors as opaque and cannot resolve them.
    config_setdefault(app.config, "myst_heading_anchors", 4)

    # MyST's default slug function uses GitHub-style heading IDs that keep leading
    # digits ("3.3 Toolchain Management" -> "33-toolchain-management"), but docutils'
    # make_id strips them ("toolchain-management"). Since Sphinx section IDs are
    # generated by docutils, the two algorithms disagree whenever a heading starts
    # with a numeric prefix, causing myst.xref_missing warnings on valid cross-
    # references. Aligning MyST's slug function on make_id fixes the mismatch.
    config_setdefault(app.config, "myst_heading_slug_func", "docutils.nodes.make_id")

    # enable "..."-syntax in markdown — must come after myst_parser is loaded above
    if isinstance(app.config.myst_enable_extensions, list):
        app.config.myst_enable_extensions.append("colon_fence")
    elif isinstance(app.config.myst_enable_extensions, set):
        app.config.myst_enable_extensions.add("colon_fence")
    else:
        print(
            "Unexpected type for myst_enable_extensions: %s",
            type(app.config.myst_enable_extensions),
        )

    return {
        "version": "3.0.0",
        # Keep this in sync with the score_docs_as_code version in MODULE.bazel
        "env_version": 300,  # 3.0.0
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
