# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@aspect_rules_py//py:defs.bzl", "py_library")
load("@rules_java//java:java_binary.bzl", "java_binary")
load("@rules_python//python:pip.bzl", "compile_pip_requirements")

# These are only exported because they're passed as files to the //docs.bzl
# macros, and thus must be visible to other packages. They should only be
# referenced by the //docs.bzl macros.

exports_files(
    [
        "requirements.txt",
        "requirements_py314.txt",
        "requirements.in",
        "dummy.py",
        "generate_sourcelinks_cli.py",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all_sources",
    srcs = glob(
        ["*.py"],
    ) + [
        "//src/docs_cli:all_sources",
        "//src/extensions/score_draw_uml_funcs:all_sources",
        "//src/extensions/score_layout:all_sources",
        "//src/extensions/score_metamodel:all_sources",
        "//src/extensions/score_mounts:all_sources",
        "//src/extensions/score_source_code_linker:all_sources",
        "//src/extensions/score_sphinx_bundle:all_sources",
        "//src/extensions/score_sphinx_needs_templates:all_sources",
        "//src/extensions/score_sync_toml:all_sources",
        "//src/extensions/score_metrics:all_sources",
        "//src/helper_lib:all_sources",
    ],
    visibility = ["//visibility:public"],
)

java_binary(
    name = "plantuml",
    jvm_flags = ["-Djava.awt.headless=true"],
    main_class = "net.sourceforge.plantuml.Run",
    visibility = ["//visibility:public"],
    runtime_deps = [
        "@plantuml//jar",
    ],
)

# This makes it possible for py_venv to depend on plantuml.
# Note: py_venv can only depend on py_library.
# TODO: This can be removed with the next
# upgrade of `aspect_rules_py` since the py_venv rule now supports a data field
py_library(
    name = "plantuml_for_python",
    srcs = ["@score_docs_as_code//src:dummy.py"],
    data = ["@score_docs_as_code//src:plantuml"],
    visibility = ["//visibility:public"],
)

# In order to update the requirements, change the `requirements.in` file and run:
# `bazel run //src:requirements.update`.
# This will update the `requirements.txt` file.
# The additional Python 3.14 lock is maintained from the same input file with
# its matching Bazel toolchain selected:
# `bazel run --@rules_python//python/config_settings:python_version=3.14 //src:requirements_py314.update`.
# To upgrade all dependencies to their latest versions, run:
# `bazel run //src:requirements.update -- --upgrade`.
compile_pip_requirements(
    name = "requirements",
    srcs = [
        "requirements.in",
    ],
    requirements_txt = "requirements.txt",
    tags = [
        "manual",
    ],
)

compile_pip_requirements(
    name = "requirements_py314",
    # Keep the Python version selector in pip-compile's generated header so
    # developers regenerate this lock with its matching toolchain.
    env = {
        "CUSTOM_COMPILE_COMMAND": "bazel run --@rules_python//python/config_settings:python_version=3.14 //src:requirements_py314.update",
    },
    srcs = [
        "requirements.in",
    ],
    requirements_txt = "requirements_py314.txt",
    tags = [
        "manual",
    ],
)

# Running this executes the `collect_source_files.bzl` aspect.
# Collects all source files from specified targets in 'deps', and makes them available for parsing for the source_code_linker

# Needed for Dash tool to check python dependency licenses.
filegroup(
    name = "requirements_lock",
    srcs = [
        "requirements.txt",
        "requirements_py314.txt",
    ],
    visibility = ["//visibility:public"],
)
